# Generated by Django 5.2.12 on 2026-03-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_tasks_assignee_attachments_comments_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование'),
        ),
    ]
