# Generated by Django 5.2.12 on 2026-03-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_tags_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationTasks',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('task_manager.tasks',),
        ),
    ]
