# Generated by Django 5.2.12 on 2026-04-10 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0004_educationtasks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationtasks',
            options={'verbose_name': 'Образовательная задача', 'verbose_name_plural': 'Образовательные задачи'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.CharField(max_length=64, verbose_name='Текст комментария'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='task_manager.projects'),
        ),
    ]
