# Generated by Django 5.2.12 on 2026-04-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0005_alter_educationtasks_options_alter_tasks_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='attachments', verbose_name='Фото'),
        ),
    ]
