# Generated by Django 5.2.12 on 2026-04-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_attachments_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachments',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='Фото'),
        ),
    ]
