# Generated by Django 5.2.12 on 2026-04-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0007_alter_attachments_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='attachments', verbose_name='Файл'),
        ),
    ]
